///////////////////////////////////////////////////////////////////////////////
// AMCONTROLInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "AMCONTROLServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
