///////////////////////////////////////////////////////////////////////////////
// AMCONTROLServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_AMCONTROL = 0x3F000000;
#define SRVNAME_AMCONTROL "AMCONTROL"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_AMCONTROLCAMCONTROL = {0x21936aed,0xb9c5,0x4134,{0xab,0xf7,0x43,0x54,0xb3,0xd9,0x8f,0x68}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_AMCONTROLParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_086E0EDC_52A2_4CE7_BF11_B19D3246607E_INCLUDED_)
#define _TC_TYPE_086E0EDC_52A2_4CE7_BF11_B19D3246607E_INCLUDED_
typedef struct _COORDINATE
{
	float fX;
	float fY;
	float fZ;
} COORDINATE, *PCOORDINATE;
#endif // !defined(_TC_TYPE_086E0EDC_52A2_4CE7_BF11_B19D3246607E_INCLUDED_)

#if !defined(_TC_TYPE_B7923ECB_AB6E_4ECF_8E2C_97DF8062D915_INCLUDED_)
#define _TC_TYPE_B7923ECB_AB6E_4ECF_8E2C_97DF8062D915_INCLUDED_
typedef struct _MUSCLE
{
	SHORT nPWM;
	SHORT nFan;
	float fTemperature;
} MUSCLE, *PMUSCLE;
#endif // !defined(_TC_TYPE_B7923ECB_AB6E_4ECF_8E2C_97DF8062D915_INCLUDED_)

#if !defined(_TC_TYPE_8658B7FE_FC19_4A02_A6E2_45C5697D8362_INCLUDED_)
#define _TC_TYPE_8658B7FE_FC19_4A02_A6E2_45C5697D8362_INCLUDED_
typedef struct _IMU
{
	COORDINATE sRotation;
	COORDINATE sGyro;
	COORDINATE sAcc;
} IMU, *PIMU;
#endif // !defined(_TC_TYPE_8658B7FE_FC19_4A02_A6E2_45C5697D8362_INCLUDED_)

#if !defined(_TC_TYPE_7C4606FA_C5B7_4059_AFBA_7C05703163D3_INCLUDED_)
#define _TC_TYPE_7C4606FA_C5B7_4059_AFBA_7C05703163D3_INCLUDED_
typedef struct _JOINT
{
	MUSCLE sMuscleF;
	MUSCLE sMuscleR;
	IMU sIMU;
	float fPos;
} JOINT, *PJOINT;
#endif // !defined(_TC_TYPE_7C4606FA_C5B7_4059_AFBA_7C05703163D3_INCLUDED_)

#if !defined(_TC_TYPE_D5CCCFB0_E7B8_4CA7_A534_6D1819B62361_INCLUDED_)
#define _TC_TYPE_D5CCCFB0_E7B8_4CA7_A534_6D1819B62361_INCLUDED_
typedef struct _COORDINATE_RAW
{
	SHORT nX;
	SHORT nY;
	SHORT nZ;
} COORDINATE_RAW, *PCOORDINATE_RAW;
#endif // !defined(_TC_TYPE_D5CCCFB0_E7B8_4CA7_A534_6D1819B62361_INCLUDED_)

#if !defined(_TC_TYPE_0D2DBD1D_0A06_4EBE_89BA_5F7D9D53BAF4_INCLUDED_)
#define _TC_TYPE_0D2DBD1D_0A06_4EBE_89BA_5F7D9D53BAF4_INCLUDED_
typedef struct _IMU_RAW
{
	COORDINATE_RAW sRotation;
	COORDINATE_RAW sGyro;
	COORDINATE_RAW sAcc;
} IMU_RAW, *PIMU_RAW;
#endif // !defined(_TC_TYPE_0D2DBD1D_0A06_4EBE_89BA_5F7D9D53BAF4_INCLUDED_)

#if !defined(_TC_TYPE_50AD0575_6798_49CC_85D7_EEE0CE1FC90E_INCLUDED_)
#define _TC_TYPE_50AD0575_6798_49CC_85D7_EEE0CE1FC90E_INCLUDED_
#pragma pack(push,1)
typedef struct _DRIVE_IN
{
	USHORT nStatusWord;
	LONG nActPos;
	USHORT nErrorCode;
} DRIVE_IN, *PDRIVE_IN;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_50AD0575_6798_49CC_85D7_EEE0CE1FC90E_INCLUDED_)

#if !defined(_TC_TYPE_BD169D18_ABA0_456F_A5BD_7C22EFF87660_INCLUDED_)
#define _TC_TYPE_BD169D18_ABA0_456F_A5BD_7C22EFF87660_INCLUDED_
#pragma pack(push,1)
typedef struct _DRIVE_OUT
{
	USHORT nControlWord;
	LONG nPos;
	char nMode;
} DRIVE_OUT, *PDRIVE_OUT;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_BD169D18_ABA0_456F_A5BD_7C22EFF87660_INCLUDED_)

typedef struct _AMCONTROLParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} AMCONTROLParameter, *PAMCONTROLParameter;

#pragma pack(push,1)
typedef struct _AMCONTROLInputs
{
	IMU_RAW sIMU_Raw[7];
	ULONG nTemperature_Raw[12];
	DRIVE_IN sDrive_In[2];
	USHORT pEncRaw[7];
} AMCONTROLInputs, *PAMCONTROLInputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _AMCONTROLOutputs
{
	SHORT nFan_Out;
	SHORT nPWM_Out[12];
	DRIVE_OUT sDrive_Out[2];
} AMCONTROLOutputs, *PAMCONTROLOutputs;
#pragma pack(pop)

typedef struct _AMCONTROLControl
{
	JOINT sTarget[7];
	JOINT sRef[7];
	JOINT sAct[7];
	JOINT sPrev[7];
} AMCONTROLControl, *PAMCONTROLControl;

#pragma pack(push,1)
typedef struct _AMCONTROLAdsCmd
{
	SHORT nEncReset;
	double fControlTime;
} AMCONTROLAdsCmd, *PAMCONTROLAdsCmd;
#pragma pack(pop)

typedef struct _AMCONTROLSetupInfo
{
	SHORT pEncHome[7];
} AMCONTROLSetupInfo, *PAMCONTROLSetupInfo;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_AMCONTROLInputs 0
#define ADI_AMCONTROLOutputs 1
#define ADI_AMCONTROLControl 3
#define ADI_AMCONTROLAdsCmd 4
#define ADI_AMCONTROLSetupInfo 5
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
