///////////////////////////////////////////////////////////////////////////////
// AMCONTROLClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "AMCONTROLClassFactory.h"
#include "AMCONTROLServices.h"
#include "AMCONTROLVersion.h"
#include "AMCONTROL.h"

BEGIN_CLASS_MAP(CAMCONTROLClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_AMCONTROLCAMCONTROL, SRVNAME_AMCONTROL "!CAMCONTROL", CAMCONTROL)
///</AutoGeneratedContent>
END_CLASS_MAP()

CAMCONTROLClassFactory::CAMCONTROLClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_AMCONTROL));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(AMCONTROL));
#endif //defined(TCDBG_UNIT_VERSION)
}

